export const RouteNames = {
    HOME: 'home',
    DASHBOARD: 'dashboard',
    PROJECT: 'project',
    MESSAGE: 'message',
    CLIENT: 'client',
    TEAMS: 'teams',
    MEETINGS: 'notifications',
    REFERRALS: 'referrals',
    SERVICES: 'services',
    CONTRACTS: 'contracts',
    INVOICES: 'invoices',
    FORMS: 'forms',
    FINANCES: 'finances',
    ADDPRODUCTS: 'addproduct',
    LOGIN: 'login',
    SIGNUP: 'signup',
    SINGLEVIDEO: 'child-video',
    SUBDETAILSPAGE: 'task-details',
    GETUSERPAGE: 'user-details',
    TEAMPAGE: 'team',
    SUBSCRIPTION: 'subscription',
    PAYMENTSELECTION: 'payment-selection',
    STRIPE: 'stripe',
    WHOP: 'whop',
    PAYMENTSUCCESS: 'success',

    // SUPER ADMIN CONSTANTS
    ADMINLAYOUT: 'adminlayout',
    ADMINDASHBOARD: 'admindashboard',
    CUSTOMERMANAGMENT: 'customer-managment',
    NOTIFICATIONorMESSAGES: 'notification&messages',
    PLANMANAGMENT: 'plan-managment',
    TRANSITIONorBILLING: 'transition&billing',
    UNAUTOHRIZE: 'unauthorize',

    // ADMINPLANS: 'adminplans',
    // ADMINPAGE1: 'adminpage1',
    // ADMINPAGE2: 'adminpage2',
    // ADMINPAGE3: 'adminpage3',

    // BASIC: 'basic',
    // PREMIUM: 'premium',
    // STANDARD: 'standard',
    // REQUEST: 'request',
    // PLANREQUEST: 'planRequest',
    SUPERADMINLOGIN: 'superadminlogin',

    CHECKOUT: 'checkout',
    ADMINPROFILEPAGE: 'profilePage'
};